name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: jobtracker
  ENVIRONMENT: dev

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::107411014674:role/github-jobtracker-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: |
          cd environment/${{ env.ENVIRONMENT }}
          terraform init

      - name: Terraform Plan
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_ec2_key_pair_name: keyweb
        run: |
          cd environment/${{ env.ENVIRONMENT }}
          terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_ec2_key_pair_name: keyweb
        run: |
          cd environment/${{ env.ENVIRONMENT }}
          terraform apply -auto-approve tfplan

      - name: Infrastructure Deployment Complete
        run: |
          echo "✓ Infrastructure deployed successfully!"
          echo "Environment: ${{ env.ENVIRONMENT }}"
          echo "Timestamp: $(date)"

      - name: Trigger Application Deployment
        if: success()
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy Application
          ref: ${{ github.ref }}